#!/bin/sh
export JAVA_HOME="/app/jre"
export PATH="/app/jre/bin:$PATH"

export HMCL_USER_HOME="${HMCL_USER_HOME:-$XDG_DATA_HOME/hmcl}"
export HMCL_LOCAL_HOME="${HMCL_LOCAL_HOME:-$HMCL_USER_HOME/local-stable}"
export HMCL_DEPENDENCIES_DIR="${HMCL_DEPENDENCIES_DIR:-$HMCL_USER_HOME/dependencies}"

exec /app/jre/bin/java \
  -jar /app/lib/hmcl/hmcl.jar "$@"
