on:
    push:
        branches:
            - main
        tags:
            - 'v*.*.*'
name: CI
jobs:
    flatpak:
        name: Flatpak
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
            options: --privileged
        strategy:
            fail-fast: false
            matrix:
                variant:
                - arch: x86_64
                  runner: ubuntu-24.04
                - arch: aarch64
                  runner: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v4
              name: Checkout
            - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
              name: Build Flatpak
              with:
                    bundle: net.huangyuhui.hmcl.Launcher-${{ matrix.variant.arch }}.flatpak
                    manifest-path: net.huangyuhui.hmcl.Launcher.yml
                    arch: ${{ matrix.variant.arch }}
                    cache-key: flatpak-builder-${{ github.sha }}
                    verbose: true


